### ISSUE TITLE
✨Create first enemy art and animation

### ISSUE THREAD

**Issue by LeonardoTPereira** [LeonardoTPereira/GGJ2023#10]
# Overview
Create the art and animation for the first enemy, a mindless zombie ant

# Expected Behavior
Will make the enemy pretty and add value for the game, allowing the devs to add this asset to the game.

# Tasks
- [ ] Sketch the enemy
- [ ] Draw the idle sprite
- [ ] Draw the walking animation
- [ ] Draw a death animation

# Additional Information
The enemy will be a black ant, taken by the cordyceps fungus. White eyes and a lot of funghi roots around it.

# Screenshots
![image](https://user-images.githubusercontent.com/5765851/215932555-f2d7be39-93aa-4208-9174-1d0162adb8fb.png)
![image](https://user-images.githubusercontent.com/5765851/215932627-b099650a-f1bb-4249-a3ed-fdef228eb877.png)
![image](https://user-images.githubusercontent.com/5765851/215932684-53c9972f-4de3-41f8-9f63-41173a3b5f5d.png)
