### ISSUE TITLE
✨Create particles related to the first gun

### ISSUE THREAD

**Issue by amandou** [LeonardoTPereira/GGJ2023#11]
# Expected Behavior
When the player is shooting the gun must have a visual feedback of the shooting action.

# Tasks
- [x] Gun's smoke particle
- [x] Gun's bullet particle
- [x] Muzzle Flash particle

#Benchmarks

# Screenshots
Show gifs when the particles are finished
