### ISSUE TITLE
✨Player health system

### ISSUE THREAD

**Issue by LeonardoTPereira** [LeonardoTPereira/GGJ2023#12]
# Overview
Adds a health system for the player, allowing it to take damage, heal and die.

# Expected Behavior
Creates the health system, allowing for the basic game loop of player losing the game to happen.

# Tasks
- [x] Set player health to max when starting level
- [x] Create method to reduce player health when taking damage
- [x] Create method to kill player when health reaches zero
- [x] Create method to check player collision with enemies to give damage
- [x] Create method to check player collision with enemy bullets to give damage
- [x] Create method to check player collision with hazards to give damage
- [x] Create method to check player collision with pits to give damage
- [x] Create method to heal player when colliding with a healing item
