### ISSUE TITLE
✨Player Health UI

### ISSUE THREAD

**Issue by LeonardoTPereira** [LeonardoTPereira/GGJ2023#13]
# Overview
Create UI to show player health

# Expected Behavior
Will show player current health, allowing player to check their conditions.  Updates when damaged or healed, and resets when starting a level.

# Tasks
- [ ] Create health UI with a heart sprite for each HP
- [ ] Create listener for the damaging events from the health controller, to update UI accordingly
- [ ] Create listener for healing events from the health controller, to update UI accordingly
- [ ] Create listener for level start to update UI to full health.
