### ISSUE TITLE
✨First Boss: Mad Mantis

### ISSUE THREAD

**Issue by LeonardoTPereira** [LeonardoTPereira/GGJ2023#14]
# Overview
Create the behavior for the first boss, the Mad Mantis

# Expected Behavior
Create the state machine and behaviors for the boss, which will act uniquely across 3 stages according to its health. This allows the player to fight and interesting boss.

# Tasks
- [x] Use animator to create the boss FSM
- [x] Create an opening state to display presentation animation
- [x] Create idle animation state
- [x] Create vertical attack animation state
- [x] Create horizontal attack animation state
- [x] Create jumping attack animation state
- [x] Create flying animation state
- [x] Create overlapping flying and attacking animation state
- [x] Creates transition animation between stage 1 and 2 (angry)

# Screenshots
![Mad Mantis](https://user-images.githubusercontent.com/5765851/216058795-07f574e5-a7d2-462f-9b54-89f6626caffa.gif)

Sources for mockup gif:
http://spritefx.blogspot.com/2013/04/sprite-slash.html 
https://www.castlevaniacrypt.com/wp-content/img/cotm/sprites/death-mantis.png
https://forums.rpgmakerweb.com/proxy.php?image=http%3A%2F%2Fi1301.photobucket.com%2Falbums%2Fag109%2Fmetanocturne%2Fpost-21751-0-44646400-1409511154_zpsjxotdt2d.png&hash=d4decc837209125384842b28b5d76dfd
