### ISSUE TITLE
✨Player camera system

### ISSUE THREAD

**Issue by yuji-teoi** [LeonardoTPereira/GGJ2023#17]
# Overview
Implement the main camera that follows the player

# Expected Behavior
The camera needs to follow the player, but should not ultrapass the game room limits

# Tasks
- [x] Virtual camera using Cinemachine
- [x] System to jump to another room in the same scene
- [x] Ajust cinemachine settings (temporarily)
