### ISSUE TITLE
✨Create collectables system

### ISSUE THREAD

**Issue by angelobguido** [LeonardoTPereira/GGJ2023#22]
# Overview
Develop a way to the player collect things.

# Expected Behavior
We expect the player to be abble to collect "coins", weapons and life.

# Tasks
- [ ] Create a generic way to visualize the collectables.
- [ ] Implement coins
- [ ] Implement weapons to collect
- [ ] Implement life collectables
