### ISSUE TITLE
✨Create player movement for a platformer

### ISSUE THREAD

**Issue by LeonardoTPereira** [LeonardoTPereira/GGJ2023#3]
#Overview
Create a prefab and attach a script able to move sideways and jump

#Expected Behavior
The prefab will be able to collide with other colliders and move, using the rigidbody 2D physics. The script must get the input from the player (using the new input system) and move or jump, according to each input.

#Tasks
- [x] Create game object with a 2D collider
- [x] Add a rigidbody2D component to handle physics
- [x] Add new input system to project
- [x] Create action mapping
- [x] Add mapping to player's GO
- [x] Create script to handle input and move to left (A and left joystick's left) and right (D and left joystick's right)
- [x] Add method in script to read spacebar and X button to jump
- [x] Add collider in player's feet to handle jump-state and know when it's touching the ground.

#Additional Information
Use Tarodev's tutorial as a base https://www.youtube.com/watch?v=3sWTzMsmdx8
