### ISSUE TITLE
✨Implement enemies animations in Unity

### ISSUE THREAD

**Issue by angelobguido** [LeonardoTPereira/GGJ2023#35]
# Tasks
- [x] Implement enemy 1 animation
- [x] Implement enemy 2 animation
- [x] Implement enemy 3 animation
