### ISSUE TITLE
✨Create player interactions with enemies

### ISSUE THREAD

**Issue by angelobguido** [LeonardoTPereira/GGJ2023#38]
# Overview
This feature will take care of the existing behaviors with player and enemies.

# Tasks
- [ ] Create a way to enemies do contact damage
- [ ] Create a way to projectiles damage player
- [ ] Create a way to players hit enemies
