### ISSUE TITLE
Audio manager and sounds✨

### ISSUE THREAD

**Issue by yuji-teoi** [LeonardoTPereira/GGJ2023#56]
# Overview
Add an audio manager to play sounds. Also add sounds.

# Expected Behavior
How will it benefit the player or the devs? What is expected of it when it is ready?

# Tasks
- [x] Add an Audio Manager
- [ ] Add sounds to the project
- [ ] Define when the sounds will be played
