### ISSUE TITLE
♻️Background parallax

### ISSUE THREAD

**Issue by yuji-teoi** [LeonardoTPereira/GGJ2023#61]
# Overview
Update parallax configurations.
Change background sprite Layers.
Fix Y axis parallax factor.

# What code could be improved?
Refactor a script to deal with Y axis parallax at Assets/Scripts/Scenario/Background/Parallax.cs
Add a script to change parallax factors more easily at Assets/Scripts/Scenario/Background/ParallaxConfigs.cs

# Tasks
- [x] Update parallax configurations.
- [x] Change background sprite Layers.
- [x] Fix Y axis parallax factor.

# Screenshots
