### ISSUE TITLE
✨Setting menu UI and configs

### ISSUE THREAD

**Issue by yuji-teoi** [LeonardoTPereira/GGJ2023#68]
# Overview
Add setting menu to main-menu and pause-menu

# Expected Behavior
Settings menu to change resolution and game volume, using UI Toolkit.

# Tasks
- [x] Settings menu uss (unity css)
- [x] Settings menu interactions via scripts
- [x] Fix bugs related to menu UI

# Additional Information
The css should be modified latter, with new additions of UI sprites and with the artist/team feedbacks.

# Screenshots
