### ISSUE TITLE
♻️Refactor forest tiles and tilerules 

### ISSUE THREAD

**Issue by yuji-teoi** [LeonardoTPereira/GGJ2023#69]
# Overview
Add new tiles to the game and delete old ones.

# What code could be improved?
New tiles and tile rules should be implemented in the first gameplay scene. 
Old tiles, tilerules and gameobjects related to old tiles should be deleted.

# Tasks
- [ ] Treat tile sprites to be functional with tile rules
- [ ] Create new tile rules using those new tiles
- [ ] Delete old tiles, tile rules and gameobjects related to old tiles
