### ISSUE TITLE
✨First Enemy Script and Enemy Basics

### ISSUE THREAD

**Issue by LeonardoTPereira** [LeonardoTPereira/GGJ2023#7]
# Overview
Create the most basic enemy, which only moves left

# Expected Behavior
Implements the behavior of the most basic enemy: a zombie ant which will move only to the left when it spawns. Will be despawned when leaving the screen after some time.

# Tasks
- [x] Create script to move the enemy only to the left
- [x] Create health controller for enemies to kill them when health reaches 0
- [x] Create enemy prefab with collider and rigidbody to enable physics and collision
- [x] Add colliders on a child object from the camera that are half a screen (or farther) away from its view and add a script to it so when something collides with it, its deleted.
- [x] Adds method to delete the enemy when dead
