### ISSUE TITLE
✨Add normal map to player and enemies

### ISSUE THREAD

**Issue by amandou** [LeonardoTPereira/GGJ2023#70]
# Tasks
- [x] Add normal map to enemy 1
- [x] Add normal map to enemy 2
- [x] Add normal map to enemy 3
- [x] Add normal map to player

# Screenshots
