### ISSUE TITLE
✨Create player sprites and animations

### ISSUE THREAD

**Issue by LeonardoTPereira** [LeonardoTPereira/GGJ2023#8]
# Overview
Creates the player sprite and the animations for being idle, walking, jumping, taking damage and dying.

# Expected Behavior
Adds the visuals for the player, making the game prettier.

# Tasks
- [x] Draw player idle sprite
- [x] Draw player idle animation
- [x] Draw player walk animation
- [x] Draw player jump animation
- [ ] Draw player hit animation
- [x] Draw player death animation

# Additional Information
The player is a red soldier ant, with a gun in hand and a military cap in its head.

# Screenshots
![image](https://user-images.githubusercontent.com/5765851/215929600-333c1a50-c61e-4a4e-b56f-35e8dbe2d6ed.png)
