### ISSUE TITLE
✨Juicy Game Main Screen

### ISSUE THREAD

**Issue by amandou** [LeonardoTPereira/GGJ2023#86]
# Overview
Make the game main screen more juicy and attractive to retain player's attention.

# Expected Behavior
How will it benefit the player or the devs? What is expected of it when it is ready?

# Tasks
- [ ] #79 
- [ ] Add leaves particles
- [ ] Add background sound
- [ ] Add buttons sound

# Additional Information
Add any other context about the feature here.

# Screenshots
If applicable, select screenshots and images which may help to explain the feature.
