### ISSUE TITLE
🐛  Fix Main Menu to use the correct images (tree, etc.)

### ISSUE THREAD

**Issue by LeonardoTPereira** [LeonardoTPereira/GGJ2023#87]
# Overview
Main Menu is with the old images, not using the tree and other background which already exist.

# To Reproduce
Open Game/Game_0 scene

# Tasks
- [x] Add the correct images
- [x] Check if the layout is responsible
- [x] Check if everything is well aligned and adjusted
- [x] Increase highlight when hovering mouse

# Screenshots
![image](https://user-images.githubusercontent.com/5765851/223437058-08156ec8-e73d-4a94-976f-c901a5f6a590.png)
