### ISSUE TITLE
✨Make Main Menu controller-friendly

### ISSUE THREAD

**Issue by LeonardoTPereira** [LeonardoTPereira/GGJ2023#88]
# Overview
We expect the game to play with a controller. Therefore, we need a controller-responsive UI

# Expected Behavior
Use up-down arrows to move through options and X or Start to confirm an action.

# Tasks
- [x] Add input system UI input module to main menu scene
- [x] Define "first selected" as the "play button"
- [x] Set correct control map
- [x] Test
