### ISSUE TITLE
✨Create tiles for the level

### ISSUE THREAD

**Issue by LeonardoTPereira** [LeonardoTPereira/GGJ2023#9]
# Overview
Creates a spritesheet for the first level's tiles

# Expected Behavior
Will make the level prettier, giving the devs tiles to create a tileset with, and the tile rules to design the level.

# Tasks
- [x] Draw sketch for the level
- [x] Draw tileable tileset for the background
- [x] Draw tileable tileset for the ground
- [x] Draw tileable tileset for the platforms
- [ ] Draw props for the tileset: branches, crystals, plants, rocks, etc.
