### ISSUE TITLE
✨Create the first level with focus on level design

### ISSUE THREAD

**Issue by LeonardoTPereira** [LeonardoTPereira/GGJ2023#93]
# Overview
After we have the new tileset, we can create good levels for the MVP. Focus on designing something interesting for the player to navigate through while showing them the two first enemies in increasingly difficulty scenarios

# Expected Behavior
Will create an interesting intro stage, focusing on letting the player understand the basic controls, how to move, jump, jump to distant platforms, avoid or shoot the dumbest enemy, avoid or shoot multiple dumbest enemies, etc.

# Tasks
- [ ] Plan the new level 
- [ ] Consider the visual affordance, guiding the player to the left and their overall goals
- [ ] Introduce first the movement
- [ ] Then the jump
- [ ] Then a jump to a "safe" platform, but where the player may fall in a lower platform as a safenet
- [ ] Introduce the dumbest ant falling into a hole (and the concept of pitfalls)
- [ ] Now introduce the dumbest ant walking linearly towards the player
- [ ] Now multiple antes in a line
- [ ] Then, the patrolling ant in a limited platform, safe for the player
- [ ] Then, patrolling ants in a lower platform where the player must fall to face them
- [ ] Mix them all for the ending!

# Screenshots
Avoid this type of unreachable platform, if possible.
![image](https://user-images.githubusercontent.com/5765851/223443965-dcbfca0c-b1c0-4bd1-bbed-e157f400ee8f.png)
